import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "components/header/header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tool-Doc-Handsome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header as="header" />
    </>
  );
};

export default Home;
