import type { NextPage } from "next";
import Head from "next/head";
import { Container, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" maxW="container.xl" bg="red.4">
        <Text as="h1" fontWeight="bold" color="redDark.4">
          This is the main
        </Text>
      </Container>
      <Container as="footer" maxW="container.xl" bg="red.4">
        <Text as="h1" fontWeight="bold" color="redDark.4">
          This is the footer
        </Text>
      </Container>
    </>
  );
};

export default Home;
